set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g history-limit 50000
set -g focus-events on

set -gw xterm-keys on
bind -n C-Left send-keys C-Left
bind -n C-Right send-keys C-Right
bind -n C-Up send-keys C-Up
bind -n C-Down send-keys C-Down

set -g status-position bottom
set -g status-interval 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes '"opencode" "lazygit"'

source-file ~/.config/tmux/theme.conf
run '~/.tmux/plugins/tpm/tpm'
