$primary = rgb(cfbdfe)
$on_primary = rgb(35275d)
$primary_container = rgb(4c3e75)
$on_primary_container = rgb(e8ddff)
$secondary = rgb(cbc2dc)
$on_secondary = rgb(332d41)
$secondary_container = rgb(4a4458)
$on_secondary_container = rgb(e8def8)
$tertiary = rgb(efb8c8)
$on_tertiary = rgb(4a2532)
$tertiary_container = rgb(633b49)
$on_tertiary_container = rgb(ffd9e3)
$error = rgb(ffb4ab)
$on_error = rgb(690005)
$error_container = rgb(93000a)
$on_error_container = rgb(ffdad6)
$background = rgb(141218)
$on_background = rgb(e6e1e9)
$surface = rgb(141218)
$on_surface = rgb(e6e1e9)
$surface_variant = rgb(49454e)
$on_surface_variant = rgb(cac4cf)
$outline = rgb(948f99)
$outline_variant = rgb(49454e)
$shadow = rgb(000000)
$scrim = rgb(000000)
$inverse_surface = rgb(e6e1e9)
$inverse_on_surface = rgb(322f35)
$inverse_primary = rgb(64558f)
