$primary = rgb(f4b2e3)
$on_primary = rgb(4d1e46)
$primary_container = rgb(67355e)
$on_primary_container = rgb(ffd7f2)
$secondary = rgb(dbbed1)
$on_secondary = rgb(3e2a39)
$secondary_container = rgb(56404f)
$on_secondary_container = rgb(f8daed)
$tertiary = rgb(f5b9a4)
$on_tertiary = rgb(4c2618)
$tertiary_container = rgb(663c2d)
$on_tertiary_container = rgb(ffdbcf)
$error = rgb(ffb4ab)
$on_error = rgb(690005)
$error_container = rgb(93000a)
$on_error_container = rgb(ffdad6)
$background = rgb(181216)
$on_background = rgb(ecdfe5)
$surface = rgb(181216)
$on_surface = rgb(ecdfe5)
$surface_variant = rgb(4e444a)
$on_surface_variant = rgb(d2c2cb)
$outline = rgb(9b8d95)
$outline_variant = rgb(4e444a)
$shadow = rgb(000000)
$scrim = rgb(000000)
$inverse_surface = rgb(ecdfe5)
$inverse_on_surface = rgb(362e33)
$inverse_primary = rgb(824c76)
