$primary = rgb(#51D3F5)
$on_primary = rgb(#12101A)
$primary_container = rgb(#51D3F5)
$on_primary_container = rgb(#F7F9F5)
$secondary = rgb(#E8EDE4)
$on_secondary = rgb(#12101A)
$secondary_container = rgb(#E8EDE4)
$on_secondary_container = rgb(#F7F9F5)
$tertiary = rgb(#F9E5D1)
$on_tertiary = rgb(#12101A)
$tertiary_container = rgb(#F9E5D1)
$on_tertiary_container = rgb(#F7F9F5)
$error = rgb(#A18C90)
$on_error = rgb(#F7F9F5)
$error_container = rgb(#A18C90)
$on_error_container = rgb(#F7F9F5)
$background = rgb(#12101A)
$on_background = rgb(#F7F9F5)
$surface = rgb(#12101A)
$on_surface = rgb(#F7F9F5)
$surface_variant = rgb(#A5A6A3)
$on_surface_variant = rgb(#F7F9F5)
$outline = rgb(#EBEEE9)
$outline_variant = rgb(#A5A6A3)
$shadow = rgb(#3A3843)
