$primary = rgb(#51D3F5)
$on_primary = rgb(#12101A)
$primary_container = rgb(#51D3F5)
$on_primary_container = rgb(#F7F9F5)
$secondary = rgb(#E8EDE4)
$on_secondary = rgb(#12101A)
$background = rgb(#12101A)
$on_background = rgb(#F7F9F5)
$surface = rgb(#12101A)
$on_surface = rgb(#F7F9F5)
$error = rgb(#A18C90)
