$primary = rgb(cfbdfe)
$on_primary = rgb(35275d)
$primary_container = rgb(4c3e75)
$on_primary_container = rgb(e8ddff)
$secondary = rgb(cbc2dc)
$on_secondary = rgb(332d41)
$background = rgb(141218)
$on_background = rgb(e6e1e9)
$surface = rgb(141218)
$on_surface = rgb(e6e1e9)
$error = rgb(ffb4ab)
