$primary = rgb(f4b2e3)
$on_primary = rgb(4d1e46)
$primary_container = rgb(67355e)
$on_primary_container = rgb(ffd7f2)
$secondary = rgb(dbbed1)
$on_secondary = rgb(3e2a39)
$background = rgb(181216)
$on_background = rgb(ecdfe5)
$surface = rgb(181216)
$on_surface = rgb(ecdfe5)
$error = rgb(ffb4ab)
